Mise à jour githook pre-push

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -8,3 +8,12 @@ if [ $? -ne 0 ]; then
 else
     echo "✅ PHPStan analysis passed."
 fi
+
+echo "🎨 Running Laravel Pint..."
+./vendor/bin/pint
+if [ $? -ne 0 ]; then
+    echo "❌ Laravel Pint failed. Please fix the issues the command (make pintf) before pushing."
+    exit 1
+else
+    echo "✅ Laravel Pint passed."
+fi
